#!/usr/bin/env node
/**
 * Bump app version and/or build number, update timestamp.
 * Writes version.json and src/version.ts for runtime and app.config.
 *
 * Usage:
 *   node scripts/bump-version.js           # increment build + timestamp
 *   node scripts/bump-version.js patch     # bump 1.0.0 -> 1.0.1, increment build
 *   node scripts/bump-version.js minor      # bump 1.0.0 -> 1.1.0
 *   node scripts/bump-version.js major    # bump 1.0.0 -> 2.0.0
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const VERSION_JSON = path.join(ROOT, 'version.json');
const VERSION_TS = path.join(ROOT, 'src', 'version.ts');

function parseSemver(v) {
  const [major, minor, patch] = v.split('.').map(Number);
  return { major: major || 0, minor: minor || 0, patch: patch || 0 };
}

function formatSemver({ major, minor, patch }) {
  return `${major}.${minor}.${patch}`;
}

function bumpSemver(version, type) {
  const s = parseSemver(version);
  if (type === 'major') {
    s.major += 1;
    s.minor = 0;
    s.patch = 0;
  } else if (type === 'minor') {
    s.minor += 1;
    s.patch = 0;
  } else if (type === 'patch') {
    s.patch += 1;
  }
  return formatSemver(s);
}

function run() {
  const bumpType = process.argv[2] || null; // null = only build + timestamp

  let data = { version: '1.0.0', build: 1, timestamp: new Date().toISOString() };
  if (fs.existsSync(VERSION_JSON)) {
    data = { ...data, ...JSON.parse(fs.readFileSync(VERSION_JSON, 'utf8')) };
  }

  if (bumpType && ['patch', 'minor', 'major'].includes(bumpType)) {
    data.version = bumpSemver(data.version, bumpType);
  }
  data.build = (data.build || 0) + 1;
  data.timestamp = new Date().toISOString();

  fs.writeFileSync(VERSION_JSON, JSON.stringify(data, null, 2) + '\n', 'utf8');

  const tsContent = `// Auto-generated by scripts/bump-version.js - do not edit by hand
export const appVersion = '${data.version}';
export const appBuild = ${data.build};
export const appTimestamp = '${data.timestamp}';
export const versionString = \`\${appVersion} (\${appBuild}) \${appTimestamp}\`;
`;

  fs.mkdirSync(path.dirname(VERSION_TS), { recursive: true });
  fs.writeFileSync(VERSION_TS, tsContent, 'utf8');

  console.log(`Version ${data.version} (build ${data.build}) @ ${data.timestamp}`);
}

run();
