// Auto-generated by scripts/bump-version.js - do not edit by hand
export const appVersion = '1.0.0';
export const appBuild = 2;
export const appTimestamp = '2026-03-04T17:42:16.623Z';
export const versionString = `${appVersion} (${appBuild}) ${appTimestamp}`;
