// Auto-generated by scripts/bump-version.js - do not edit by hand
export const appVersion = '1.1.0';
export const appBuild = 4;
export const appTimestamp = '2026-07-04T17:48:38.391Z';
export const versionString = `${appVersion} (${appBuild}) ${appTimestamp}`;
