// Auto-generated by scripts/bump-version.js - do not edit by hand
export const appVersion = '1.0.1';
export const appBuild = 3;
export const appTimestamp = '2026-05-30T17:37:58.923Z';
export const versionString = `${appVersion} (${appBuild}) ${appTimestamp}`;
